### ISSUE TITLE
Missing Package and non-existent method

### ISSUE THREAD

**Issue by rjtmahinay** [rjtmahinay/vessel-reporting#6]
Problems in #5 @jmgang 
1. SpecificServiceHelper class is not checked-in
2. **objectToListObject** method in ListConversionHelper is not checked-in
3. **isBlank()** method in String. Is this in a new String package? this is used in ReportService, VesselReportingController and NotificationController

![image](https://user-images.githubusercontent.com/20996624/90986276-253f4980-e5b4-11ea-96ac-c70012015773.png)

![image](https://user-images.githubusercontent.com/20996624/90986281-32f4cf00-e5b4-11ea-8114-6cd4514cbdeb.png)

**Comment by rjtmahinay** [comment]
@

**Comment by jmgang** [comment]
Hi Tristan,

Missing classes and files have been added and updated. You may check the latest pull request.

Regarding the isBlank() method, yes that is part of the String class. 

Regards

**Comment by rjtmahinay** [comment]
Verified changes. Closing issue
